name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
    # Optional: Trigger on tag creation (e.g., v1.0, v2.0)
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  # Use your Docker Hub username and repo name here
  # Format: username/repository-name
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/netsecgame

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up QEMU (Optional: only needed if you want to build for multiple architectures like ARM64)
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # This step extracts metadata (tags, labels) for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }} # Don't push on PRs, just build
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max


      # DO NOT PUBLISH THE WHITEBOX VERSION FOR NOW
      # # Extract metadata (tags, labels) for Docker Whitebox variant
      # - name: Extract Docker metadata (Whitebox)
      #   id: meta-whitebox
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: ${{ env.IMAGE_NAME }}
      #     flavor: |
      #       latest=auto
      #       suffix=-whitebox,onlatest=true
      #     tags: |
      #       type=raw,value=latest,enable={{is_default_branch}}
      #       type=ref,event=branch
      #       type=ref,event=tag
      #       type=sha

      # - name: Build and push Docker image (Whitebox)
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     push: ${{ github.event_name != 'pull_request' }} # Don't push on PRs, just build
      #     tags: ${{ steps.meta-whitebox.outputs.tags }}
      #     labels: ${{ steps.meta-whitebox.outputs.labels }}
      #     build-args: |
      #       GAME_MODULE=netsecgame.game.worlds.WhiteBoxNetSecGame
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max
